import { payslipTotals } from '@/data/payroll'
import type { Payslip } from '@/types'
import { formatCurrency, formatDate } from './format'

/** Plain-text payslip used for the "Download" action. */
export function payslipText(p: Payslip) {
  const t = payslipTotals(p)
  const line = (label: string, amount: number) => `  ${label.padEnd(34, '.')} ${formatCurrency(amount, true).padStart(12)}`
  return [
    'NORTHWIND GROUP — PAYSLIP',
    '='.repeat(52),
    `Pay period:     ${p.period}`,
    `Pay date:       ${formatDate(p.payDate)}`,
    'Employee:       Ahmed Hassan (EMP-1042)',
    'Position:       Senior Software Engineer — Technology',
    'Bank:           CIB · EG38 •••• 8000 2',
    `Paid days:      ${p.paidDays} of ${p.workingDays}`,
    '',
    'EARNINGS',
    ...p.earnings.map((l) => line(l.label, l.amount)),
    line('Gross salary', t.gross),
    '',
    'DEDUCTIONS',
    ...p.deductions.map((l) => line(l.label, l.amount)),
    line('Total deductions', t.deductions),
    '',
    '='.repeat(52),
    line('NET PAY', t.net),
    '',
    'This payslip was generated by the HRMS demo environment.',
  ].join('\n')
}
